services:
  - type: web
    name: jobsro-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jobsro-db
          property: connectionString

databases:
  - name: jobsro-db
    plan: free